PROMPT TABLES with initial data... 
PROMPT CHIA_FILTERED_MINS      3 rows exported
PROMPT COUNTRIES             127 rows exported
PROMPT CUSTOMER_TYPES          7 rows exported
PROMPT DEFAULT_UNLI_PARAMS     1 rows exported
PROMPT HLR_SERVERS            32 rows exported
PROMPT HLR_SERVER_MAPPING    428 rows exported
PROMPT IN_SERVERS              4 rows exported
PROMPT IN_SERVER_MAPPING     397 rows exported
PROMPT KEYWORDS               16 rows exported
PROMPT KEYWORD_MSG           112 rows exported
PROMPT MCC_MESSAGES           80 rows exported
PROMPT MODULES                 9 rows exported
PROMPT ROAMING_PARTNERS       46 rows exported
PROMPT SERVICES                4 rows exported
PROMPT SSET_MAPPING           16 rows exported
PROMPT USER_MASTER          5325 rows exported
PROMPT USER_ROLES             10 rows exported
PROMPT ZONES                   4 rows exported


PROMPT create table "ACL"... 
PROMPT create table "AMBITION"...
PROMPT create table "ARDSREQUEST"...
PROMPT create table "ARDSRESPONSE"...
PROMPT create table "BLACKLISTED_ERR_LOG"...
PROMPT create table "BLACKLISTED_LOG"...
PROMPT create table "BLACKLISTED_WHITELISTED_LOG"...
PROMPT create table "BROADCAST_LOG"...
PROMPT create table "BULK_ACTIVATION_ERR_LOG"...
PROMPT create table "BULK_DEACTIVATION_ERR_LOG"...
PROMPT create table "CCB_LOG"...
PROMPT create table "COUNTRIES"...
PROMPT create table "CUSTOMER_TYPES"...
PROMPT create table "CUSTOMER_TYPES_MAPPING"...
PROMPT create table "CUSTOMER_TYPES_MAPPING_ERR"...
PROMPT create table "DAILYBAL_LOG"...
PROMPT create table "DEACT_HLR_IMSI"...
PROMPT create table "DEFAULT_UNLI_EXP"...
PROMPT create table "DEFAULT_UNLI_HIST"...
PROMPT create table "DEFAULT_UNLI_LOG"...
PROMPT create table "DEFAULT_UNLI_LOG_BKUP"...
PROMPT create table "DEFAULT_UNLI_PARAMS"...
PROMPT create table "DEL"...
PROMPT create table "DUP"...
PROMPT create table "FOR_DEACT"...
PROMPT create table "FOUND"...
PROMPT create table "FUN"...
PROMPT create table "FUN_HLR"...
PROMPT create table "FUN_IN"...
PROMPT create table "FUN_NSN2"...
PROMPT create table "FUN_ORIG"...
PROMPT create table "GEO_PROBE_LOG"...
PROMPT create table "GLOBE_SIM"...
PROMPT create table "HLR"...
PROMPT create table "HLR_DEACT"...
PROMPT create table "HLR_IMSI_MAPPING"...
PROMPT create table "HLR_IN"...
PROMPT create table "HLR_SERVERS"...
PROMPT create table "HLR_SERVER_MAPPING"...
PROMPT create table "IN_SERVERS"...
PROMPT create table "IN_SERVER_MAPPING"...
PROMPT create table "KEYWORDREQUEST"...
PROMPT create table "KEYWORDREQUEST_HISTORY"...
PROMPT create table "KEYWORDS"...
PROMPT create table "KEYWORD_MSG"...
PROMPT create table "MANUAL_ENROLLMENT_LOG"...
PROMPT create table "MANUAL_ENROLLMENT_LOG_HISTORY"...
PROMPT create table "MCC_MESSAGES"...
PROMPT create table "MODULES"...
PROMPT create table "MSISDN_IMSI"...
PROMPT create table "NOTIFICATION_LOG"...
PROMPT create table "NSN"...
PROMPT create table "ODS_LOG"...
PROMPT create table "OLDFUN"...
PROMPT create table "PASS_LOG"...
PROMPT create table "PLMN_MAPPING"...
PROMPT create table "PLMN_MAPPING_STAGE"...
PROMPT create table "PROD_MESSAGES"...
PROMPT create table "RADCOM_DOWNLOADED_FILES"...
PROMPT create table "RECON_DEL"...
PROMPT create table "RECON_FUN"...
PROMPT create table "RECON_HLR"...
PROMPT create table "RECON_IN"...
PROMPT create table "REQUEST_LOG"...
PROMPT create table "REQUEST_LOG_HISTORY"...
PROMPT create table "RESPONSE_LOG"...
PROMPT create table "RESPONSE_LOG_HISTORY"...
PROMPT create table "RETRY_FAILED_DEACT_LOG"...
PROMPT create table "ROAMING_PARTNERS"...
PROMPT create table "SERVICES"...
PROMPT create table "SIM_ACTIVATION"...
PROMPT create table "SIM_ACTIVATION_HISTORY"...
PROMPT create table "SIM_ACTIVATION_LINKS"...
PROMPT create table "SIM_ACTIVATION_LINKS_2ND"...
PROMPT create table "SIM_ACTIVATION_LINKS_ERR_BULK"...
PROMPT create table "SIM_ACTIVATION_LINKS_FUNBK"...
PROMPT create table "SIM_ACTIVATION_LINKS_TMP"...
PROMPT create table "SIM_ACTIVATION_LINK_EXPIRED"...
PROMPT create table "SIM_DEACT_LINKS_ERR_BULK"...
PROMPT create table "SIM_SERVICES"...
PROMPT create table "SSET_MAPPING"...
PROMPT create table "SWITCH"...
PROMPT create table "SWITCHED"...
PROMPT create table "SYSTEM_LOG"...
PROMPT create table "SYSTEM_MSG"...
PROMPT create table "TAGGING"...
PROMPT create table "TAG_PAIR"...
PROMPT create table "TMP"...
PROMPT create table "TMP2"...
PROMPT create table "TMP_ACT"...
PROMPT create table "TMP_MCC_MESSAGES"...
PROMPT create table "TRANSACTION_LOG"...
PROMPT create table "TRG"...
PROMPT create table "UPLOAD"...
PROMPT create table "USER_LOG"...
PROMPT create table "USER_MASTER"...
PROMPT create table "USER_ROLES"...
PROMPT create table "USURF_COUNTRIES"...
PROMPT create table "USURF_ACTIVATION"...
PROMPT create table "WHITELISTED_ERR_LOG"...
PROMPT create table "WHITELISTED_LOG"...
PROMPT create table "ZONES"...

CREATE TABLE "ACL"
   (    "ID" NUMBER(11,0) NOT NULL ENABLE,
        "ROLE_CODE" VARCHAR2(30),
        "MOD_NAME" VARCHAR2(255),
        "CAN_VIEW" NUMBER(1,0) DEFAULT 1,
        "CAN_UPDATE" NUMBER(1,0) DEFAULT 0,
        "CAN_DELETE" NUMBER(1,0) DEFAULT 0,
        "CAN_ADD" NUMBER(1,0) DEFAULT 0,
        "CAN_APPROVE" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE,
        "CAN_RELEASE" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE,
        "CAN_PROCESS" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE,
        "CAN_CANCEL" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE,
        "CREATED_BY" VARCHAR2(32) NOT NULL ENABLE,
        "DT_CREATED" DATE NOT NULL ENABLE,
        "UPDATED_BY" VARCHAR2(32),
        "DT_UPDATED" DATE,
        "LAST_UPDATED" DATE,
         CONSTRAINT "ACL_PK" PRIMARY KEY ("ID"),
         CONSTRAINT "ACL_UK" UNIQUE ("ROLE_CODE", "MOD_NAME")
   );



CREATE TABLE "AMBITION"
   (    "MSISDN" NUMBER NOT NULL ENABLE
   );



CREATE TABLE "ARDSREQUEST"
   (    "ID" NUMBER NOT NULL ENABLE,
        "IMSI" VARCHAR2(36) NOT NULL ENABLE,
        "OPERATION" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE,
        "STATUS" NUMBER(4,0) DEFAULT 0 NOT NULL ENABLE,
        "RNA" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE,
        "START_TM" DATE NOT NULL ENABLE,
        "END_TM" DATE,
         CONSTRAINT "ARDSREQUEST_PK" PRIMARY KEY ("ID")
   );



CREATE TABLE "ARDSRESPONSE"
   (    "ID" NUMBER NOT NULL ENABLE,
        "IMSI" VARCHAR2(36) NOT NULL ENABLE,
        "ENROLLMENT_TYPE" VARCHAR2(12) NOT NULL ENABLE,
        "STATUS" NUMBER(4,0) DEFAULT 0 NOT NULL ENABLE,
        "CAUSE" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE,
        "START_TM" DATE NOT NULL ENABLE,
        "END_TM" DATE,
         CONSTRAINT "ARDSRESPONSE_PK" PRIMARY KEY ("ID")
   );



CREATE TABLE "BLACKLISTED_ERR_LOG"
   (    "MSISDN" VARCHAR2(30),
        "DT_CREATED" DATE,
        "REMARKS" VARCHAR2(255),
        "TRAN_DT" DATE,
        "CREATED_BY" VARCHAR2(30),
        "BULK_GRP_ID" VARCHAR2(30),
        "REASON" VARCHAR2(128)
   );



CREATE TABLE "BLACKLISTED_LOG"
   (    "MSISDN" NUMBER NOT NULL ENABLE,
        "DT_CREATED" DATE NOT NULL ENABLE,
        "REMARKS" VARCHAR2(255),
        "TRAN_DT" DATE,
        "CREATED_BY" VARCHAR2(30),
        "BULK_GRP_ID" VARCHAR2(30),
         CONSTRAINT "BLISTED_LOG_PK" PRIMARY KEY ("MSISDN")
   );



CREATE TABLE "BLACKLISTED_WHITELISTED_LOG"
   (    "MSISDN" NUMBER NOT NULL ENABLE,
        "ACTION" VARCHAR2(12) NOT NULL ENABLE,
        "DT_CREATED" DATE NOT NULL ENABLE,
        "REMARKS" VARCHAR2(255),
        "TRAN_DT" DATE,
        "CREATED_BY" VARCHAR2(30),
        "BULK_GRP_ID" VARCHAR2(30)
   );



CREATE TABLE "BROADCAST_LOG"
   (    "ID" NUMBER NOT NULL ENABLE,
        "MSISDN" NUMBER(12,0) NOT NULL ENABLE,
        "MESSAGE_ID" VARCHAR2(60),
        "TX_DATE" DATE NOT NULL ENABLE,
        "STATUS" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE,
        "CLUSTER_NODE" NUMBER(3,0) DEFAULT 1 NOT NULL ENABLE,
        "MSG" VARCHAR2(2000),
         CONSTRAINT "BROADCAST_LOG_PK" PRIMARY KEY ("ID"),
         CONSTRAINT "BROADCAST_LOG_UK" UNIQUE ("MSISDN", "TX_DATE", "MESSAGE_ID") DISABLE
   );



CREATE TABLE "BULK_ACTIVATION_ERR_LOG"
   (    "MSISDN" NUMBER,
        "TX_DATE" DATE,
        "CS_USERNAME" VARCHAR2(30),
        "CS_REASON" VARCHAR2(512),
        "DT_CREATED" DATE,
        "SUBS_NAME" VARCHAR2(128),
        "SUBS_CONTACT_NO" VARCHAR2(128),
        "REMARKS" VARCHAR2(255),
        "BULK_GRP_ID" VARCHAR2(30)
   );



CREATE TABLE "BULK_DEACTIVATION_ERR_LOG"
   (    "MSISDN" NUMBER,
        "TX_DATE" DATE,
        "CS_USERNAME" VARCHAR2(30),
        "CS_REASON" VARCHAR2(512),
        "DT_CREATED" DATE,
        "SUBS_NAME" VARCHAR2(128),
        "SUBS_CONTACT_NO" VARCHAR2(128),
        "REMARKS" VARCHAR2(255),
        "BULK_GRP_ID" VARCHAR2(30)
   );



CREATE TABLE "CHIA_FILTERED_MINS"
( ID NUMBER NOT NULL ENABLE,
  MSISDN_FR NUMBER,
  MSISDN_TO NUMBER,
  BRAND   VARCHAR2(12) DEFAULT 'POSTPAID' NOT NULL ENABLE,
  STATUS  VARCHAR2(12) DEFAULT 'ACTIVE' NOT NULL ENABLE,
  CREATED_BY VARCHAR2(30),
  DT_CREATED DATE,
  UPDATED_BY VARCHAR2(30),
  DT_UPDATED DATE,
   CONSTRAINT chia_filtered_mins_pk PRIMARY KEY (ID)
);



CREATE TABLE "CCB_LOG"
   (    "ID" NUMBER NOT NULL ENABLE,
        "MSISDN" VARCHAR2(16) NOT NULL ENABLE,
        "CCB_ACTION" VARCHAR2(8) NOT NULL ENABLE,
        "CCB_STATUS" VARCHAR2(8),
        "STATUS" NUMBER DEFAULT 0 NOT NULL ENABLE,
        "CLUSTER_NODE" NUMBER(3,0) DEFAULT 1 NOT NULL ENABLE,
        "TX_DATE" DATE,
        "DT_CREATED" DATE,
         CONSTRAINT "ccb_log_PK" PRIMARY KEY ("ID")
   );



CREATE TABLE "COUNTRIES"
   (    "ID" NUMBER NOT NULL ENABLE,
        "COUNTRY_CODE" VARCHAR2(30) NOT NULL ENABLE,
        "COUNTRY_NAME" VARCHAR2(60),
        "ZONE_ID" NUMBER NOT NULL ENABLE,
        "STATUS" VARCHAR2(12) NOT NULL ENABLE,
        "CREATED_BY" VARCHAR2(30),
        "DT_CREATED" DATE,
        "UPDATED_BY" VARCHAR2(30),
        "DT_UPDATED" DATE,
        "COUNTRY_NAME_UPPER" VARCHAR2(60),
        "CHARGE_DESC" VARCHAR2(255),
         CONSTRAINT "COUNTRIES_PK" PRIMARY KEY ("ID"),
         CONSTRAINT "COUNTRIES_UK" UNIQUE ("COUNTRY_CODE"),
         CONSTRAINT "COUNTRY_ZONE_FK" FOREIGN KEY ("ZONE_ID")
          REFERENCES "ZONES" ("ZONE_ID") ENABLE
   );



CREATE TABLE "CUSTOMER_TYPES"
   (    "ID" NUMBER NOT NULL ENABLE,
        "CUSTOMER_TYPE" VARCHAR2(16) NOT NULL ENABLE,
        "DAILY_BALANCE" NUMBER(4,0) DEFAULT 0 NOT NULL ENABLE,
        "MAX_DURATION" NUMBER,
        "MIN_VOICE" NUMBER,
        "SMS_TRESHOLD" NUMBER,
        "STATUS" VARCHAR2(12) NOT NULL ENABLE,
        "CREATED_BY" VARCHAR2(30),
        "DT_CREATED" DATE,
        "UPDATED_BY" VARCHAR2(30),
        "DT_UPDATED" DATE,
        "MIN_BALANCE" NUMBER,
        "EXT_MIN_BALANCE" NUMBER,
        "BREATHING_PERIOD" NUMBER(3,0),
        "PRE_ACT_DAY" NUMBER(3,0),
        "NUM_LINK" NUMBER(3,0),
        "MAX_INACTIVITY_DAYS" NUMBER(4,0),
        "WARNING_DEACT_DAYS" NUMBER(4,0),
        "ARDS_1ST_NOTIFY" NUMBER,
        "ARDS_2ND_NOTIFY" NUMBER,
        "ARDS_TMP_DURATION" NUMBER,
         CONSTRAINT "CUST_TYPE_PK" PRIMARY KEY ("ID"),
         CONSTRAINT "CUST_TYPE_UK" UNIQUE ("CUSTOMER_TYPE")
   );



CREATE TABLE "CUSTOMER_TYPES_MAPPING"
   (    "ID" NUMBER NOT NULL ENABLE,
        "CUSTOMER_TYPE" VARCHAR2(16) NOT NULL ENABLE,
        "MSISDN_FR" NUMBER,
        "MSISDN_TO" NUMBER,
        "STATUS" VARCHAR2(12) NOT NULL ENABLE,
        "CREATED_BY" VARCHAR2(30),
        "DT_CREATED" DATE,
        "UPDATED_BY" VARCHAR2(30),
        "DT_UPDATED" DATE,
        "BULK_GRP_ID" VARCHAR2(30),
         CONSTRAINT "CUST_TYPE_MAP_PK" PRIMARY KEY ("ID"),
         CONSTRAINT "CUST_TYPE_MAP_UK" UNIQUE ("CUSTOMER_TYPE", "MSISDN_FR"),
         CONSTRAINT "CUST_TYPE_MAP_FK" FOREIGN KEY ("CUSTOMER_TYPE")
          REFERENCES "CUSTOMER_TYPES" ("CUSTOMER_TYPE") ENABLE
   );



CREATE TABLE "CUSTOMER_TYPES_MAPPING_ERR"
   (    "CUSTOMER_TYPE" VARCHAR2(128),
        "MSISDN_FR" VARCHAR2(128),
        "MSISDN_TO" VARCHAR2(128),
        "REASON" VARCHAR2(128),
        "CREATED_BY" VARCHAR2(30),
        "DT_CREATED" DATE,
        "UPDATED_BY" VARCHAR2(30),
        "DT_UPDATED" DATE,
        "BULK_GRP_ID" VARCHAR2(30)
   );



CREATE TABLE "DAILYBAL_LOG"
   (    "ID" NUMBER NOT NULL ENABLE,
        "MSISDN" VARCHAR2(16) NOT NULL ENABLE,
        "TX_DATE" DATE NOT NULL ENABLE,
        "STATUS" NUMBER DEFAULT 0 NOT NULL ENABLE,
        "CLUSTER_NODE" NUMBER(3,0) DEFAULT 1 NOT NULL ENABLE,
        "DAILY_BALANCE" NUMBER(4,0) NOT NULL ENABLE,
        "LAST_DAILY_BAL_CTR" NUMBER(2,0) NOT NULL ENABLE,
         CONSTRAINT "dailybal_log_PK" PRIMARY KEY ("ID"),
         CONSTRAINT "dailybal_log_UK" UNIQUE ("MSISDN", "TX_DATE")
   );



CREATE TABLE "DEACT_HLR_IMSI"
   (    "IMSI" VARCHAR2(30)
   );



CREATE TABLE "DEFAULT_UNLI_EXP"
   (    "ID" NUMBER NOT NULL ENABLE,
        "MSISDN" VARCHAR2(12) NOT NULL ENABLE,
        "TRAN_DT" DATE NOT NULL ENABLE,
        "TRAN_TM" DATE NOT NULL ENABLE,
        "MCC" VARCHAR2(30) NOT NULL ENABLE,
        "MNC" VARCHAR2(30) NOT NULL ENABLE,
        "STATUS" NUMBER DEFAULT 0 NOT NULL ENABLE,
        "ORIGINAL_DT" DATE NOT NULL ENABLE,
        "PRE_EXPIRY_DT" DATE NOT NULL ENABLE,
        "PRE_EXPIRY_TM" DATE NOT NULL ENABLE,
        "EXPIRY_DT" DATE NOT NULL ENABLE,
        "EXPIRY_TM" DATE NOT NULL ENABLE,
         CONSTRAINT "DEFAULT_UNLI_EXP_PK" PRIMARY KEY ("ID"),
         CONSTRAINT "DEFAULT_UNLI_EXP_UK" UNIQUE ("MCC", "MSISDN")
   );



CREATE TABLE "DEFAULT_UNLI_HIST"
   (    "ID" NUMBER NOT NULL ENABLE,
        "MSISDN" VARCHAR2(12) NOT NULL ENABLE,
        "TRAN_DT" DATE NOT NULL ENABLE,
        "TRAN_TM" DATE NOT NULL ENABLE,
        "MNC" VARCHAR2(30) NOT NULL ENABLE,
        "MCC" VARCHAR2(30) NOT NULL ENABLE,
        "SGSN_IP" VARCHAR2(30) NOT NULL ENABLE,
        "STATUS" NUMBER DEFAULT 0 NOT NULL ENABLE,
        "PRE_EXPIRY_DT" DATE NOT NULL ENABLE,
        "PRE_EXPIRY_TM" DATE NOT NULL ENABLE,
        "EXPIRY_DT" DATE NOT NULL ENABLE,
        "EXPIRY_TM" DATE NOT NULL ENABLE,
        "ORIGINAL_DT" DATE NOT NULL ENABLE,
        "DT_CREATED" DATE NOT NULL ENABLE,
        "DT_DELETED" DATE NOT NULL ENABLE,
        "FILE_NAME" VARCHAR2(100) NOT NULL ENABLE,
         CONSTRAINT "DEFAULT_UNLI_HIST_PK" PRIMARY KEY ("ID")
   );



CREATE TABLE "DEFAULT_UNLI_LOG"
   (    "ID" NUMBER(11,0) NOT NULL ENABLE,
        "MSISDN" VARCHAR2(30) NOT NULL ENABLE,
        "TRAN_DT" DATE NOT NULL ENABLE,
        "TRAN_TM" DATE NOT NULL ENABLE,
        "MNC" VARCHAR2(30) NOT NULL ENABLE,
        "MCC" VARCHAR2(60) NOT NULL ENABLE,
        "SGSN_IP" VARCHAR2(30) NOT NULL ENABLE,
        "STATUS" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE,
        "EXPIRY_DATE" DATE NOT NULL ENABLE,
        "DT_CREATED" DATE NOT NULL ENABLE,
        "FILE_NAME" VARCHAR2(100) NOT NULL ENABLE,
         CONSTRAINT "DEFAULT_UNLI_LOG_PK" PRIMARY KEY ("ID"),
         CONSTRAINT "DEFAULT_UNLI_LOG_UK" UNIQUE ("MSISDN", "MCC")
   );



CREATE TABLE "DEFAULT_UNLI_LOG_BKUP"
   (    "ID" NUMBER NOT NULL ENABLE,
        "MSISDN" VARCHAR2(12) NOT NULL ENABLE,
        "TRAN_DT" DATE NOT NULL ENABLE,
        "TRAN_TM" DATE NOT NULL ENABLE,
        "MCC" VARCHAR2(30) NOT NULL ENABLE,
        "MNC" VARCHAR2(30) NOT NULL ENABLE,
        "STATUS" NUMBER NOT NULL ENABLE,
        "ORIGINAL_DT" DATE NOT NULL ENABLE,
        "PRE_EXPIRY_DT" DATE NOT NULL ENABLE,
        "PRE_EXPIRY_TM" DATE NOT NULL ENABLE,
        "EXPIRY_DT" DATE NOT NULL ENABLE,
        "EXPIRY_TM" DATE NOT NULL ENABLE
   );



CREATE TABLE "DEFAULT_UNLI_PARAMS"
   (    "PARAM_ID" VARCHAR2(30) NOT NULL ENABLE,
        "PARAM_CHAR_VALUE" VARCHAR2(60),
        "PARAM_NUM1_VALUE" NUMBER,
        "PARAM_NUM2_VALUE" NUMBER,
        "PARAM_DESCRIPTION" VARCHAR2(60),
         CONSTRAINT "DEFAULT_UNLI_PARAMS_PK" PRIMARY KEY ("PARAM_ID")
   );



CREATE TABLE "DEL"
   (    "MSISDN" NUMBER NOT NULL ENABLE
   );



CREATE TABLE "DUP"
   (    "MSISDN" NUMBER NOT NULL ENABLE
   );



CREATE TABLE "FOR_DEACT"
   (    "ID" NUMBER NOT NULL ENABLE,
        "TRAN_DT" DATE,
        "A_NO" VARCHAR2(20) NOT NULL ENABLE,
        "B_NO" VARCHAR2(20),
        "MSG" VARCHAR2(320),
        "STEP_NO" NUMBER(4,0) NOT NULL ENABLE,
        "LAST_STEP_NO" NUMBER(4,0) NOT NULL ENABLE,
        "STATUS" NUMBER(4,0) NOT NULL ENABLE,
        "DT_CREATED" DATE NOT NULL ENABLE,
        "DT_MODIFIED" DATE,
        "TXID" VARCHAR2(128),
        "TRAN_TYPE" NUMBER(2,0),
        "CLUSTER_NODE" NUMBER NOT NULL ENABLE,
        "CUSTOMER_TYPE" VARCHAR2(16),
        "REQUEST_ORIGIN" VARCHAR2(8) NOT NULL ENABLE,
        "REF_ID" NUMBER,
        "MIN_BAL" NUMBER(4,0) NOT NULL ENABLE,
        "STEP_SEQ" VARCHAR2(32),
        "ERROR_CODE" NUMBER(4,0),
        "IMSI" VARCHAR2(30),
        "DURATION" NUMBER,
        "ACTIVATION_DATE" VARCHAR2(32),
        "DEACTIVATION_DATE" VARCHAR2(32),
        "GSM_NUM" VARCHAR2(20),
        "RESULT_CODE" NUMBER(12,0) NOT NULL ENABLE,
        "SILENT" NUMBER(1,0) NOT NULL ENABLE,
        "BREATHING_PERIOD" NUMBER(4,0)
   );



CREATE TABLE "FOUND"
   (    "IMSI" VARCHAR2(30)
   );



CREATE TABLE "FUN"
   (    "MSISDN" NUMBER NOT NULL ENABLE,
        "IMSI" VARCHAR2(30)
   );



CREATE TABLE "FUN_HLR"
   (    "MSISDN" NUMBER NOT NULL ENABLE,
        "IMSI" VARCHAR2(30)
   );



CREATE TABLE "FUN_IN"
   (    "MSISDN" NUMBER NOT NULL ENABLE,
        "IMSI" VARCHAR2(30)
   );



CREATE TABLE "FUN_NSN2"
   (    "MSISDN" NUMBER NOT NULL ENABLE,
        "IMSI" VARCHAR2(30)
   );



CREATE TABLE "FUN_ORIG"
   (    "MSISDN" NUMBER NOT NULL ENABLE,
        "LINK_TO" VARCHAR2(12) NOT NULL ENABLE,
         CONSTRAINT "FUN_ORIG_PK" PRIMARY KEY ("MSISDN", "LINK_TO")
   );



CREATE TABLE "GEO_PROBE_LOG"
   (    "ID" NUMBER NOT NULL ENABLE,
        "IMSI" VARCHAR2(30),
        "SCCP" VARCHAR2(30),
        "STATUS" NUMBER DEFAULT 0 NOT NULL ENABLE,
        "TX_DATE" DATE,
        "DT_CREATED" DATE,
        "CLUSTER_NODE" NUMBER(3,0) DEFAULT 1 NOT NULL ENABLE,
         CONSTRAINT "GEO_PROBE_LOG_PK" PRIMARY KEY ("ID")
   );



CREATE TABLE "GLOBE_SIM"
   (    "MSISDN" NUMBER NOT NULL ENABLE
   );



CREATE TABLE "HLR"
   (    "IMSI" VARCHAR2(30)
   );



CREATE TABLE "HLR_DEACT"
   (    "ID" NUMBER NOT NULL ENABLE,
        "TRAN_DT" DATE,
        "A_NO" VARCHAR2(20) NOT NULL ENABLE,
        "B_NO" VARCHAR2(20),
        "MSG" VARCHAR2(320),
        "STEP_NO" NUMBER(4,0) NOT NULL ENABLE,
        "LAST_STEP_NO" NUMBER(4,0) NOT NULL ENABLE,
        "STATUS" NUMBER(4,0) NOT NULL ENABLE,
        "DT_CREATED" DATE NOT NULL ENABLE,
        "DT_MODIFIED" DATE,
        "TXID" VARCHAR2(128),
        "TRAN_TYPE" NUMBER(2,0),
        "CLUSTER_NODE" NUMBER NOT NULL ENABLE,
        "CUSTOMER_TYPE" VARCHAR2(16),
        "REQUEST_ORIGIN" VARCHAR2(8) NOT NULL ENABLE,
        "REF_ID" NUMBER,
        "MIN_BAL" NUMBER(4,0) NOT NULL ENABLE,
        "STEP_SEQ" VARCHAR2(32),
        "ERROR_CODE" NUMBER(4,0),
        "IMSI" VARCHAR2(30),
        "DURATION" NUMBER,
        "ACTIVATION_DATE" VARCHAR2(32),
        "DEACTIVATION_DATE" VARCHAR2(32),
        "GSM_NUM" VARCHAR2(20),
        "RESULT_CODE" NUMBER(12,0) NOT NULL ENABLE,
        "SILENT" NUMBER(1,0) NOT NULL ENABLE,
        "BREATHING_PERIOD" NUMBER(4,0)
   );



CREATE TABLE "HLR_IMSI_MAPPING"
   (    "SERVER_IP" VARCHAR2(14) NOT NULL ENABLE,
        "IMSI" VARCHAR2(15) NOT NULL ENABLE,
        "STATUS" VARCHAR2(12) DEFAULT 'ACTIVE' NOT NULL ENABLE,
        "SERVER_NAME" VARCHAR2(30) NOT NULL ENABLE,
        "CREATED_BY" VARCHAR2(30) NOT NULL ENABLE,
        "DT_CREATED" DATE NOT NULL ENABLE,
        "MODIFIED_BY" VARCHAR2(30),
        "DT_MODIFIED" DATE,
        "ID" NUMBER,
         CONSTRAINT "IMSI_PK" PRIMARY KEY ("ID"),
         CONSTRAINT "IMSI_UK" UNIQUE ("SERVER_NAME", "IMSI")
   );



CREATE TABLE "HLR_IN"
   (    "MSISDN" NUMBER NOT NULL ENABLE,
        "IMSI" VARCHAR2(30)
   );



CREATE TABLE "HLR_SERVERS"
   (    "ID" NUMBER NOT NULL ENABLE,
        "SERVER_IP" VARCHAR2(30) NOT NULL ENABLE,
        "SERVER_PORT" VARCHAR2(30),
        "SERVER_NAME" VARCHAR2(60) NOT NULL ENABLE,
        "USERNAME" VARCHAR2(60) NOT NULL ENABLE,
        "PASSWORD" VARCHAR2(60) NOT NULL ENABLE,
        "TIMEOUT" NUMBER NOT NULL ENABLE,
        "RETRY_CNT" NUMBER NOT NULL ENABLE,
        "STATUS" VARCHAR2(12) NOT NULL ENABLE,
        "CREATED_BY" VARCHAR2(30),
        "DT_CREATED" DATE,
        "UPDATED_BY" VARCHAR2(30),
        "DT_UPDATED" DATE,
         CONSTRAINT "HLR_SERVERS_PK" PRIMARY KEY ("ID"),
         CONSTRAINT "HLR_SERVERS_UK" UNIQUE ("SERVER_NAME")
   );



CREATE TABLE "HLR_SERVER_MAPPING"
   (    "ID" NUMBER NOT NULL ENABLE,
        "SERVER_NAME" VARCHAR2(60) NOT NULL ENABLE,
        "MSISDN_FR" NUMBER,
        "MSISDN_TO" NUMBER,
        "STATUS" VARCHAR2(12) NOT NULL ENABLE,
        "CREATED_BY" VARCHAR2(30),
        "DT_CREATED" DATE,
        "UPDATED_BY" VARCHAR2(30),
        "DT_UPDATED" DATE,
         CONSTRAINT "HLR_SERVER_MAPPING_PK" PRIMARY KEY ("ID"),
         CONSTRAINT "HLR_SERVER_MAPPING_UK" UNIQUE ("SERVER_NAME", "MSISDN_FR"),
         CONSTRAINT "HLR_SERVER_MAPPING_FK" FOREIGN KEY ("SERVER_NAME")
          REFERENCES "HLR_SERVERS" ("SERVER_NAME") ENABLE
   );



CREATE TABLE "IN_SERVERS"
   (    "ID" NUMBER NOT NULL ENABLE,
        "SERVER_IP" VARCHAR2(30) NOT NULL ENABLE,
        "SERVER_PORT" VARCHAR2(30),
        "SERVER_NAME" VARCHAR2(60) NOT NULL ENABLE,
        "USERNAME" VARCHAR2(60) NOT NULL ENABLE,
        "PASSWORD" VARCHAR2(60) NOT NULL ENABLE,
        "TIMEOUT" NUMBER NOT NULL ENABLE,
        "RETRY_CNT" NUMBER NOT NULL ENABLE,
        "STATUS" VARCHAR2(12) NOT NULL ENABLE,
        "CREATED_BY" VARCHAR2(30),
        "DT_CREATED" DATE,
        "UPDATED_BY" VARCHAR2(30),
        "DT_UPDATED" DATE,
        "SVC_NAME" VARCHAR2(64),
        "EXPIRY" VARCHAR2(64),
         CONSTRAINT "IN_SERVERS_PK" PRIMARY KEY ("ID"),
         CONSTRAINT "IN_SERVERS_UK" UNIQUE ("SERVER_NAME")
   );



CREATE TABLE "IN_SERVER_MAPPING"
   (    "ID" NUMBER NOT NULL ENABLE,
        "SERVER_NAME" VARCHAR2(60) NOT NULL ENABLE,
        "MSISDN_FR" NUMBER,
        "MSISDN_TO" NUMBER,
        "STATUS" VARCHAR2(12) NOT NULL ENABLE,
        "CREATED_BY" VARCHAR2(30),
        "DT_CREATED" DATE,
        "UPDATED_BY" VARCHAR2(30),
        "DT_UPDATED" DATE,
         CONSTRAINT "IN_SERVER_MAPPING_PK" PRIMARY KEY ("ID"),
         CONSTRAINT "IN_SERVER_MAPPING_UK" UNIQUE ("SERVER_NAME", "MSISDN_FR"),
         CONSTRAINT "IN_SERVER_MAPPING_FK" FOREIGN KEY ("SERVER_NAME")
          REFERENCES "IN_SERVERS" ("SERVER_NAME") ENABLE
   );



CREATE TABLE "KEYWORDREQUEST"
   (    "ID" NUMBER NOT NULL ENABLE,
        "MSISDN" VARCHAR2(36) NOT NULL ENABLE,
        "IMSI" VARCHAR2(36),
        "ENROLLMENT_TYPE" VARCHAR2(12) NOT NULL ENABLE,
        "STATUS" NUMBER(4,0) DEFAULT 0 NOT NULL ENABLE,
        "START_TM" DATE NOT NULL ENABLE,
        "END_TM" DATE,
        "REF_ID" NUMBER NOT NULL ENABLE,
         CONSTRAINT "KEYWORDREQUEST_PK" PRIMARY KEY ("ID")
   );



CREATE TABLE "KEYWORDREQUEST_HISTORY"
   (    "ID" NUMBER NOT NULL ENABLE,
        "MSISDN" VARCHAR2(36) NOT NULL ENABLE,
        "IMSI" VARCHAR2(36),
        "ENROLLMENT_TYPE" VARCHAR2(12) NOT NULL ENABLE,
        "STATUS" NUMBER(4,0) DEFAULT 0 NOT NULL ENABLE,
        "TX_DATE" DATE NOT NULL ENABLE,
        "START_TM" DATE NOT NULL ENABLE,
        "END_TM" DATE,
        "REF_ID" NUMBER NOT NULL ENABLE
   );


CREATE TABLE "KEYWORDS"
   (    "ID" NUMBER NOT NULL ENABLE,
        "KEYWORD" VARCHAR2(30) NOT NULL ENABLE,
        "SUB_KEYWORD" VARCHAR2(30),
        "KEYWORD_DESC" VARCHAR2(60) NOT NULL ENABLE,
        "STATUS" VARCHAR2(12) NOT NULL ENABLE,
        "CREATED_BY" VARCHAR2(30),
        "DT_CREATED" DATE,
        "UPDATED_BY" VARCHAR2(30),
        "DT_UPDATED" DATE,
         CONSTRAINT "KEYWORDS_PK" PRIMARY KEY ("ID"),
         CONSTRAINT "KEYWORDS_UK" UNIQUE ("KEYWORD", "SUB_KEYWORD")
   );



CREATE TABLE "KEYWORD_MSG"
   (    "ID" NUMBER NOT NULL ENABLE,
        "KEYWORD" VARCHAR2(30) NOT NULL ENABLE,
        "SUB_KEYWORD" VARCHAR2(30),
        "DESCRIPTION" VARCHAR2(128) NOT NULL ENABLE,
        "CUSTOMER_TYPE" VARCHAR2(16) DEFAULT 'Default' NOT NULL ENABLE,
        "MESSAGE_TYPE" VARCHAR2(30) DEFAULT 'ALERT' NOT NULL ENABLE,
        "MSG_1" VARCHAR2(2000) NOT NULL ENABLE,
        "MSG_2" VARCHAR2(320),
        "MSG_3" VARCHAR2(320),
        "STATUS" VARCHAR2(12) NOT NULL ENABLE,
        "CREATED_BY" VARCHAR2(30),
        "DT_CREATED" DATE,
        "UPDATED_BY" VARCHAR2(30),
        "DT_UPDATED" DATE,
        "MESSAGE_ID" VARCHAR2(60),
         CONSTRAINT "KEYWORD_MSG_PK" PRIMARY KEY ("ID"),
         CONSTRAINT "KEYWORD_MSG_UK" UNIQUE ("MESSAGE_ID"),
         CONSTRAINT "KEYWORD_MSG_FK" FOREIGN KEY ("KEYWORD", "SUB_KEYWORD")
          REFERENCES "KEYWORDS" ("KEYWORD", "SUB_KEYWORD") ENABLE
   );



CREATE TABLE "MANUAL_ENROLLMENT_LOG"
   (    "ID" NUMBER NOT NULL ENABLE,
        "MSISDN" NUMBER NOT NULL ENABLE,
        "ENROLLMENT_TYPE" VARCHAR2(12) NOT NULL ENABLE,
        "BULK_UPLOAD" NUMBER NOT NULL ENABLE,
        "TX_DATE" DATE NOT NULL ENABLE,
        "STATUS" NUMBER DEFAULT 0,
        "CS_USERNAME" VARCHAR2(30),
        "CS_REASON" VARCHAR2(30),
        "DT_CREATED" DATE NOT NULL ENABLE,
        "DT_MODIFIED" DATE,
        "SUBS_NAME" VARCHAR2(60),
        "SUBS_GROUP" VARCHAR2(22),
        "SUBS_CONTACT_NO" VARCHAR2(22),
        "REMARKS" VARCHAR2(255),
        "BULK_GRP_ID" VARCHAR2(30),
        "DURATION" NUMBER,
        "CLUSTER_NODE" NUMBER DEFAULT 1 NOT NULL ENABLE,
        "CUSTOMER_TYPE" VARCHAR2(16),
        "MIN_BAL" NUMBER DEFAULT 0,
        "BREATHING_PERIOD" NUMBER(4,0),
        "LINK_TO" NUMBER(12,0),
        "REQUEST_ORIGIN" VARCHAR2(8) DEFAULT 'WEB',
        "OTHER_TYPE" VARCHAR2(30),
        "SILENT" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE,
        "IMSI" VARCHAR2(30),
         CONSTRAINT "MANUAL_ENROLLMENT_LOG_PK" PRIMARY KEY ("ID")
   );









CREATE TABLE "MANUAL_ENROLLMENT_LOG_HISTORY"
   (    "ID" NUMBER NOT NULL ENABLE,
        "MSISDN" NUMBER NOT NULL ENABLE,
        "ENROLLMENT_TYPE" VARCHAR2(12) NOT NULL ENABLE,
        "BULK_UPLOAD" NUMBER NOT NULL ENABLE,
        "TX_DATE" DATE NOT NULL ENABLE,
        "STATUS" NUMBER DEFAULT 0,
        "CS_USERNAME" VARCHAR2(30),
        "CS_REASON" VARCHAR2(30),
        "DT_CREATED" DATE NOT NULL ENABLE,
        "DT_MODIFIED" DATE,
        "SUBS_NAME" VARCHAR2(60),
        "SUBS_GROUP" VARCHAR2(22),
        "SUBS_CONTACT_NO" VARCHAR2(22),
        "REMARKS" VARCHAR2(255),
        "BULK_GRP_ID" VARCHAR2(30),
        "DURATION" NUMBER,
        "CLUSTER_NODE" NUMBER DEFAULT 1 NOT NULL ENABLE,
        "CUSTOMER_TYPE" VARCHAR2(16),
        "MIN_BAL" NUMBER DEFAULT 0,
        "BREATHING_PERIOD" NUMBER(4,0),
        "LINK_TO" NUMBER(12,0),
        "REQUEST_ORIGIN" VARCHAR2(8) DEFAULT 'WEB',
        "OTHER_TYPE" VARCHAR2(30),
        "SILENT" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE,
        "IMSI" VARCHAR2(30)
   );



CREATE TABLE "MCC_MESSAGES"
   (    "ID" NUMBER NOT NULL ENABLE,
        "MCC" VARCHAR2(60) NOT NULL ENABLE,
        "MESSAGE_TYPE" VARCHAR2(30) NOT NULL ENABLE,
        "MSG" VARCHAR2(2000) NOT NULL ENABLE,
        "DT_CREATED" DATE NOT NULL ENABLE,
         CONSTRAINT "MCC_MESSAGES_PK" PRIMARY KEY ("ID"),
         CONSTRAINT "MCC_MESSAGES_UK" UNIQUE ("MCC", "MESSAGE_TYPE")
   );



CREATE TABLE "MODULES"
   (    "ID" NUMBER(11,0) NOT NULL ENABLE,
        "MOD_NAME" VARCHAR2(255),
        "MOD_DESC" VARCHAR2(255),
        "CREATED_BY" VARCHAR2(32) NOT NULL ENABLE,
        "DT_CREATED" DATE NOT NULL ENABLE,
        "UPDATED_BY" VARCHAR2(32),
        "DT_UPDATED" DATE,
         CONSTRAINT "MOD_PK" PRIMARY KEY ("ID")
   );



CREATE TABLE "MSISDN_IMSI"
   (    "MSISDN" NUMBER NOT NULL ENABLE,
        "IMSI" VARCHAR2(30)
   );



CREATE TABLE "NOTIFICATION_LOG"
   (    "ID" NUMBER NOT NULL ENABLE,
        "REF_ID" NUMBER NOT NULL ENABLE,
        "MSISDN" VARCHAR2(12) NOT NULL ENABLE,
        "STATUS" NUMBER(4,0) DEFAULT 0 NOT NULL ENABLE,
        "TRAN_TYPE" NUMBER(4,0) NOT NULL ENABLE,
        "TRAN_DATE" DATE NOT NULL ENABLE,
        "DT_CREATED" DATE,
        "DT_MODIFIED" DATE,
        "CLUSTER_NODE" NUMBER(3,0) DEFAULT 1 NOT NULL ENABLE,
         CONSTRAINT "NOTIFICATION_LOG_PK" PRIMARY KEY ("ID")
   );



CREATE TABLE "NSN"
   (    "MSISDN" NUMBER NOT NULL ENABLE,
        "IMSI" VARCHAR2(30)
   );



CREATE TABLE "ODS_LOG"
   (    "ID" NUMBER NOT NULL ENABLE,
        "MSISDN" VARCHAR2(16) NOT NULL ENABLE,
        "STATUS" NUMBER DEFAULT 0 NOT NULL ENABLE,
        "CLUSTER_NODE" NUMBER(3,0) DEFAULT 1 NOT NULL ENABLE,
        "TX_DATE" DATE,
        "DT_CREATED" DATE,
         CONSTRAINT "ods_log_PK" PRIMARY KEY ("ID")
   );



CREATE TABLE "OLDFUN"
   (    "MSISDN" NUMBER NOT NULL ENABLE
   );



CREATE TABLE "PASS_LOG"
   (    "ID" NUMBER(*,0) NOT NULL ENABLE,
        "USER_CODE" VARCHAR2(30),
        "PASSWORD" VARCHAR2(255),
        "CREATED_BY" VARCHAR2(32) NOT NULL ENABLE,
        "DT_CREATED" DATE NOT NULL ENABLE,
        "UPDATED_BY" VARCHAR2(32),
        "DT_UPDATED" DATE,
         CONSTRAINT "PASS_PK" PRIMARY KEY ("ID")
   );



CREATE TABLE "PLMN_MAPPING"
   (    "ID" NUMBER NOT NULL ENABLE,
        "ADDR" VARCHAR2(30) NOT NULL ENABLE,
        "CARRIER" VARCHAR2(30) NOT NULL ENABLE,
        "COUNTRY_CODE" VARCHAR2(30) NOT NULL ENABLE,
        "HOT" NUMBER DEFAULT 0 NOT NULL ENABLE,
        "STATUS" VARCHAR2(12) NOT NULL ENABLE,
        "CREATED_BY" VARCHAR2(30),
        "DT_CREATED" DATE,
        "UPDATED_BY" VARCHAR2(30),
        "DT_UPDATED" DATE,
        "BREATHING_PERIOD" NUMBER,
        "MAX_DURATION" NUMBER,
         CONSTRAINT "PLMN_MAPPING_PK" PRIMARY KEY ("ID"),
         CONSTRAINT "PLMN_MAPPING_UK" UNIQUE ("ADDR"),
         CONSTRAINT "PLMN_COUNTRY_FK" FOREIGN KEY ("COUNTRY_CODE")
          REFERENCES "COUNTRIES" ("COUNTRY_CODE") ENABLE
   );



CREATE TABLE "PLMN_MAPPING_STAGE"
   (    "ID" NUMBER,
        "ADDR" VARCHAR2(30) NOT NULL ENABLE,
        "CARRIER" VARCHAR2(30) NOT NULL ENABLE,
        "COUNTRY_CODE" VARCHAR2(30) NOT NULL ENABLE,
        "HOT" NUMBER NOT NULL ENABLE,
        "STATUS" VARCHAR2(12) NOT NULL ENABLE,
        "CREATED_BY" VARCHAR2(30),
        "DT_CREATED" DATE,
        "UPDATED_BY" VARCHAR2(30),
        "DT_UPDATED" DATE,
        "BREATHING_PERIOD" NUMBER,
        "MAX_DURATION" NUMBER
   );



CREATE TABLE "PROD_MESSAGES"
   (    "MSG_TYPE" VARCHAR2(1),
        "CUSTOMER_TYPE" VARCHAR2(12),
        "DESCRIPTION" VARCHAR2(255),
        "KEYWORD" VARCHAR2(128),
        "MESSAGE" VARCHAR2(4000),
        "MESSAGE_ID" VARCHAR2(128)
   );



CREATE TABLE "RADCOM_DOWNLOADED_FILES"
   (    "ID" NUMBER NOT NULL ENABLE,
        "FILE_NAME" VARCHAR2(100) NOT NULL ENABLE,
        "NO_VALID" NUMBER DEFAULT 0 NOT NULL ENABLE,
        "NO_ERRORS" NUMBER DEFAULT 0 NOT NULL ENABLE,
        "DT_UPLOADED" DATE NOT NULL ENABLE,
         CONSTRAINT "RADCOM_DOWNLOADED_FILES_PK" PRIMARY KEY ("ID"),
         CONSTRAINT "RADCOM_DOWNLOADED_FILES_UK" UNIQUE ("FILE_NAME")
   );



CREATE TABLE "RECON_DEL"
   (    "MSISDN" NUMBER NOT NULL ENABLE
   );



CREATE TABLE "RECON_FUN"
   (    "MSISDN" NUMBER NOT NULL ENABLE,
        "IMSI" VARCHAR2(30)
   );



CREATE TABLE "RECON_HLR"
   (    "IMSI" VARCHAR2(30)
   );



CREATE TABLE "RECON_IN"
   (    "MSISDN" NUMBER NOT NULL ENABLE,
        "IMSI" VARCHAR2(30)
   );



CREATE TABLE "REQUEST_LOG"
   (    "ID" NUMBER NOT NULL ENABLE,
        "TRAN_DT" DATE,
        "A_NO" VARCHAR2(20) NOT NULL ENABLE,
        "B_NO" VARCHAR2(20),
        "MSG" VARCHAR2(320),
        "STEP_NO" NUMBER(4,0) DEFAULT 0 NOT NULL ENABLE,
        "LAST_STEP_NO" NUMBER(4,0) DEFAULT 0 NOT NULL ENABLE,
        "STATUS" NUMBER(4,0) DEFAULT 0 NOT NULL ENABLE,
        "DT_CREATED" DATE NOT NULL ENABLE,
        "DT_MODIFIED" DATE,
        "TXID" VARCHAR2(128),
        "TRAN_TYPE" NUMBER(2,0),
        "CLUSTER_NODE" NUMBER DEFAULT 1 NOT NULL ENABLE,
        "CUSTOMER_TYPE" VARCHAR2(16) DEFAULT 'TRIGGER',
        "REQUEST_ORIGIN" VARCHAR2(8) DEFAULT 'SMS' NOT NULL ENABLE,
        "REF_ID" NUMBER,
        "MIN_BAL" NUMBER(4,0) DEFAULT 0 NOT NULL ENABLE,
        "STEP_SEQ" VARCHAR2(32),
        "ERROR_CODE" NUMBER(4,0),
        "IMSI" VARCHAR2(30),
        "DURATION" NUMBER DEFAULT 0,
        "ACTIVATION_DATE" VARCHAR2(32),
        "DEACTIVATION_DATE" VARCHAR2(32),
        "GSM_NUM" VARCHAR2(20),
        "RESULT_CODE" NUMBER(12,0) DEFAULT 0 NOT NULL ENABLE,
        "SILENT" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE,
        "BREATHING_PERIOD" NUMBER(4,0),
        "NSN_FLAG" NUMBER(4,0) DEFAULT 0,
         CONSTRAINT "TXRE_LOG_PK" PRIMARY KEY ("ID")
   );



CREATE TABLE "REQUEST_LOG_HISTORY"
   (    "ID" NUMBER NOT NULL ENABLE,
        "TRAN_DT" DATE,
        "A_NO" VARCHAR2(20) NOT NULL ENABLE,
        "B_NO" VARCHAR2(20),
        "MSG" VARCHAR2(320),
        "STEP_NO" NUMBER(4,0) DEFAULT 0 NOT NULL ENABLE,
        "LAST_STEP_NO" NUMBER(4,0) DEFAULT 0 NOT NULL ENABLE,
        "STATUS" NUMBER(4,0) DEFAULT 0 NOT NULL ENABLE,
        "DT_CREATED" DATE NOT NULL ENABLE,
        "DT_MODIFIED" DATE,
        "TXID" VARCHAR2(128),
        "TRAN_TYPE" NUMBER(2,0),
        "CLUSTER_NODE" NUMBER DEFAULT 1 NOT NULL ENABLE,
        "CUSTOMER_TYPE" VARCHAR2(16) DEFAULT 'TRIGGER',
        "REQUEST_ORIGIN" VARCHAR2(8) DEFAULT 'SMS' NOT NULL ENABLE,
        "REF_ID" NUMBER,
        "MIN_BAL" NUMBER(4,0) DEFAULT 0 NOT NULL ENABLE,
        "STEP_SEQ" VARCHAR2(32),
        "ERROR_CODE" NUMBER(4,0),
        "IMSI" VARCHAR2(30),
        "DURATION" NUMBER DEFAULT 0,
        "ACTIVATION_DATE" VARCHAR2(32),
        "DEACTIVATION_DATE" VARCHAR2(32),
        "GSM_NUM" VARCHAR2(20),
        "RESULT_CODE" NUMBER(12,0) DEFAULT 0 NOT NULL ENABLE,
        "SILENT" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE
   );



CREATE TABLE "RESPONSE_LOG"
   (    "ID" NUMBER NOT NULL ENABLE,
        "REF_ID" NUMBER NOT NULL ENABLE,
        "TRAN_DT" DATE,
        "A_NO" VARCHAR2(20) NOT NULL ENABLE,
        "B_NO" VARCHAR2(20),
        "STATUS" NUMBER(4,0) DEFAULT 0 NOT NULL ENABLE,
        "DT_CREATED" DATE NOT NULL ENABLE,
        "DT_MODIFIED" DATE,
        "TXID" VARCHAR2(128),
        "MSG" VARCHAR2(2000) NOT NULL ENABLE,
        "CLUSTER_NODE" NUMBER DEFAULT 1 NOT NULL ENABLE,
        "CUSTOMER_TYPE" VARCHAR2(16),
        "MSG_ID" VARCHAR2(60),
        "TRAN_TYPE" NUMBER(4,0) DEFAULT 0 NOT NULL ENABLE,
         CONSTRAINT "TXRES_LOG_PK" PRIMARY KEY ("ID")
   );






CREATE TABLE "RESPONSE_LOG_HISTORY"
   (    "ID" NUMBER NOT NULL ENABLE,
        "REF_ID" NUMBER NOT NULL ENABLE,
        "TRAN_DT" DATE,
        "A_NO" VARCHAR2(20) NOT NULL ENABLE,
        "B_NO" VARCHAR2(20),
        "STATUS" NUMBER(4,0) DEFAULT 0 NOT NULL ENABLE,
        "DT_CREATED" DATE NOT NULL ENABLE,
        "DT_MODIFIED" DATE,
        "TXID" VARCHAR2(128),
        "MSG" VARCHAR2(2000) NOT NULL ENABLE,
        "CLUSTER_NODE" NUMBER DEFAULT 1 NOT NULL ENABLE,
        "CUSTOMER_TYPE" VARCHAR2(16),
        "MSG_ID" VARCHAR2(60),
        "TRAN_TYPE" NUMBER(4,0) DEFAULT 0 NOT NULL ENABLE
   );





CREATE TABLE "RETRY_FAILED_DEACT_LOG"
   (    "ID" NUMBER,
        "A_NO" VARCHAR2(20),
        "DT_REPROCESSED" DATE
   );



CREATE TABLE "ROAMING_PARTNERS"
   (    "ID" NUMBER NOT NULL ENABLE,
        "MNC" VARCHAR2(30) NOT NULL ENABLE,
        "MCC" VARCHAR2(60) NOT NULL ENABLE,
        "TZ" VARCHAR2(30) NOT NULL ENABLE,
        "DT_CREATED" DATE NOT NULL ENABLE,
         CONSTRAINT "ROAMING_PARTNERS_PK" PRIMARY KEY ("ID"),
         CONSTRAINT "ROAMING_PARTNERS_UK" UNIQUE ("MNC", "MCC")
   );





CREATE TABLE "SERVICES"
   (    "ID" NUMBER NOT NULL ENABLE,
        "SERVICE_CODE" VARCHAR2(30) NOT NULL ENABLE,
        "SERVICE_DESC" VARCHAR2(60) NOT NULL ENABLE,
        "PRIORITY" NUMBER DEFAULT 9999 NOT NULL ENABLE,
        "STATUS" VARCHAR2(12) NOT NULL ENABLE,
        "CREATED_BY" VARCHAR2(30),
        "DT_CREATED" DATE,
        "UPDATED_BY" VARCHAR2(30),
        "DT_UPDATED" DATE,
        "SVC_URL" VARCHAR2(256),
        "SVC_HOST" VARCHAR2(64),
        "SVC_PORT" NUMBER(5,0),
        "SVC_USER" VARCHAR2(32),
        "SVC_PASS" VARCHAR2(32),
        "DB_HOST" VARCHAR2(64),
        "DB_USER" VARCHAR2(32),
        "DB_PASS" VARCHAR2(32),
        "TIMEOUT_SEC" NUMBER(4,0),
        "THREAD_COUNT" NUMBER(3,0),
        "MAX_RETRY" NUMBER(2,0),
        "APP_LIB" VARCHAR2(32),
        "SVC_NAME" VARCHAR2(64),
        "EXPIRY" VARCHAR2(64),
         CONSTRAINT "SERVICES_PK" PRIMARY KEY ("ID"),
         CONSTRAINT "SERVICES_UK" UNIQUE ("SERVICE_CODE"),
         CONSTRAINT "SERVICES_STEP_UK" UNIQUE ("PRIORITY")
   );



CREATE TABLE "SIM_ACTIVATION"
   (    "ID" NUMBER NOT NULL ENABLE,
        "MSISDN" NUMBER NOT NULL ENABLE,
        "COUNTRY" VARCHAR2(30),
        "SUBSCRIBER_NAME" VARCHAR2(60),
        "NAME_OF_REQ_PARTY" VARCHAR2(60),
        "ACTIVATION_DT" DATE,
        "REACTIVATION_DT" DATE,
        "STATUS" VARCHAR2(12),
        "DEACTIVATION_DT" DATE,
        "DEACTIVATION_REASON" VARCHAR2(128),
        "CS_USERNAME" VARCHAR2(30),
        "CREATED_BY" VARCHAR2(30),
        "DT_CREATED" DATE,
        "UPDATED_BY" VARCHAR2(30),
        "DT_UPDATED" DATE,
        "REQUEST_ORIGIN" VARCHAR2(8) DEFAULT 'SMS' NOT NULL ENABLE,
        "REMARKS" VARCHAR2(255),
        "DAILY_BAL" NUMBER(8,2),
        "MIN_BAL" NUMBER(8,2),
        "DURATION" NUMBER(3,0),
        "EXTENDED" NUMBER(1,0) DEFAULT 0,
        "BREATHING_PERIOD" NUMBER(4,0),
        "LAST_DAILY_BAL_CHK" DATE,
        "LAST_COUNTRY_CHK" DATE,
        "HOT_COUNTRY_CNT" NUMBER DEFAULT 0,
        "IMSI" VARCHAR2(30),
        "LAST_DAILY_BAL" NUMBER DEFAULT 0,
        "LAST_DAILY_BAL_CTR" NUMBER(2,0) DEFAULT 0 NOT NULL ENABLE,
        "CUSTOMER_TYPE" VARCHAR2(16) DEFAULT 'TRIGGER' NOT NULL ENABLE,
        "COUNTRY_NAME" VARCHAR2(60),
        "BREATHING_PERIOD_DT" DATE,
        "HOT_COUNTRY_DT" DATE,
        "HOT_COUNTRY_DURATION" NUMBER,
        "DEACT_BASIS_DT" DATE,
        "HOT_COUNTRY_MAX_DURATION" NUMBER(6,0),
        "ACTIVATION_TM" DATE,
        "DEACTIVATION_TM" DATE,
        "NOTIFY_DATE" DATE,
        "DT_MIGRATED" DATE,
         CONSTRAINT "SIM_ACT_PK" PRIMARY KEY ("ID"),
         CONSTRAINT "SIM_ACT_UK" UNIQUE ("MSISDN"),
         CONSTRAINT "SIM_ACTIVATION_COUNTRY_FK" FOREIGN KEY ("COUNTRY")
          REFERENCES "COUNTRIES" ("COUNTRY_CODE") ENABLE
   );



CREATE TABLE "SIM_ACTIVATION_HISTORY"
   (    "ID" NUMBER NOT NULL ENABLE,
        "MSISDN" NUMBER NOT NULL ENABLE,
        "COUNTRY" VARCHAR2(30),
        "SUBSCRIBER_NAME" VARCHAR2(60),
        "NAME_OF_REQ_PARTY" VARCHAR2(60),
        "ACTIVATION_METHOD" VARCHAR2(30),
        "ACTIVATION_DT" DATE,
        "REACTIVATION_DT" DATE,
        "STATUS" VARCHAR2(12),
        "DEACTIVATION_DT" DATE,
        "DEACTIVATION_REASON" VARCHAR2(128),
        "CS_USERNAME" VARCHAR2(30),
        "CREATED_BY" VARCHAR2(30),
        "DT_CREATED" DATE,
        "UPDATED_BY" VARCHAR2(30),
        "DT_UPDATED" DATE,
        "REQUEST_ORIGIN" VARCHAR2(8) NOT NULL ENABLE,
        "REMARKS" VARCHAR2(255),
        "DAILY_BAL" NUMBER(8,2),
        "MIN_BAL" NUMBER(8,2),
        "DURATION" NUMBER(3,0),
        "EXTENDED" NUMBER(1,0),
        "BREATHING_PERIOD" NUMBER(4,0),
        "LAST_DAILY_BAL_CHK" DATE,
        "LAST_COUNTRY_CHK" DATE,
        "HOT_COUNTRY_CNT" NUMBER,
        "IMSI" VARCHAR2(30),
        "LAST_DAILY_BAL" NUMBER,
        "LAST_DAILY_BAL_CTR" NUMBER(2,0) NOT NULL ENABLE,
        "CUSTOMER_TYPE" VARCHAR2(16) NOT NULL ENABLE,
        "COUNTRY_NAME" VARCHAR2(60),
        "SIM_ACTIVATION_ID" NUMBER,
        "BREATHING_PERIOD_DT" DATE,
        "HOT_COUNTRY_DT" DATE,
        "HOT_COUNTRY_DURATION" NUMBER,
        "HOT_COUNTRY_MAX_DURATION" NUMBER(6,0),
        "ACTIVATION_TM" DATE,
        "DEACTIVATION_TM" DATE,
        "NOTIFY_DATE" DATE
   );



CREATE TABLE "SIM_ACTIVATION_LINKS"
   (    "ID" NUMBER NOT NULL ENABLE,
        "CUSTOMER_TYPE" VARCHAR2(16) NOT NULL ENABLE,
        "MSISDN" NUMBER NOT NULL ENABLE,
        "LINK_TO" VARCHAR2(12) NOT NULL ENABLE,
        "LINK_TO_TYPE" VARCHAR2(12) NOT NULL ENABLE,
        "STATUS" VARCHAR2(12) NOT NULL ENABLE,
        "CUST_ACTIVATION_DT" DATE,
        "CUST_DEACTIVATION_DT" DATE,
        "DT_CREATED" DATE,
        "DT_MODIFIED" DATE,
        "LINK_CMD" VARCHAR2(12) NOT NULL ENABLE,
        "ODS_LAST_CHK_DT" DATE,
        "EXPIRY_DATE" DATE,
        "CUST_ACTIVATION_TM" DATE,
        "CUST_DEACTIVATION_TM" DATE,
        "NOTIFY_DATE" DATE,
        "CS_USERNAME" VARCHAR2(30),
        "BULK_GRP_ID" VARCHAR2(30),
         CONSTRAINT "SIM_LINK_PK" PRIMARY KEY ("ID"),
         CONSTRAINT "SIM_LINK_UK" UNIQUE ("MSISDN", "LINK_TO")
   );



CREATE TABLE "SIM_ACTIVATION_LINKS_2ND"
   (    "ID" NUMBER,
        "CUSTOMER_TYPE" VARCHAR2(16),
        "MSISDN" NUMBER NOT NULL ENABLE,
        "LINK_TO" VARCHAR2(12) NOT NULL ENABLE,
        "LINK_TO_TYPE" VARCHAR2(12),
        "STATUS" VARCHAR2(12),
        "CUST_ACTIVATION_DT" DATE,
        "CUST_DEACTIVATION_DT" DATE,
        "DT_CREATED" DATE,
        "DT_MODIFIED" DATE,
        "LINK_CMD" VARCHAR2(12),
        "ODS_LAST_CHK_DT" DATE,
        "EXPIRY_DATE" DATE,
        "CUST_ACTIVATION_TM" DATE,
        "CUST_DEACTIVATION_TM" DATE,
        "NOTIFY_DATE" DATE,
        "CS_USERNAME" VARCHAR2(30),
        "BULK_GRP_ID" VARCHAR2(30)
   );



CREATE TABLE "SIM_ACTIVATION_LINKS_ERR_BULK"
   (    "DT_CREATED" DATE,
        "BULK_GRP_ID" VARCHAR2(30),
        "REASON" VARCHAR2(512),
        "TRAN_DT" DATE,
        "CREATED_BY" VARCHAR2(30),
        "REMARKS" VARCHAR2(512),
        "LOCAL_SIM" NUMBER,
        "OFW_SIM" NUMBER
   );



CREATE TABLE "SIM_ACTIVATION_LINKS_FUNBK"
   (    "ID" NUMBER NOT NULL ENABLE,
        "CUSTOMER_TYPE" VARCHAR2(16) NOT NULL ENABLE,
        "MSISDN" NUMBER NOT NULL ENABLE,
        "LINK_TO" VARCHAR2(12) NOT NULL ENABLE,
        "LINK_TO_TYPE" VARCHAR2(12) NOT NULL ENABLE,
        "STATUS" VARCHAR2(12) NOT NULL ENABLE,
        "CUST_ACTIVATION_DT" DATE,
        "CUST_DEACTIVATION_DT" DATE,
        "DT_CREATED" DATE,
        "DT_MODIFIED" DATE,
        "LINK_CMD" VARCHAR2(12) NOT NULL ENABLE,
        "ODS_LAST_CHK_DT" DATE,
        "EXPIRY_DATE" DATE,
        "CUST_ACTIVATION_TM" DATE,
        "CUST_DEACTIVATION_TM" DATE,
        "NOTIFY_DATE" DATE,
        "CS_USERNAME" VARCHAR2(30),
        "BULK_GRP_ID" VARCHAR2(30)
   );



CREATE TABLE "SIM_ACTIVATION_LINKS_TMP"
   (    "CUSTOMER_TYPE" CHAR(3),
        "MSISDN" NUMBER(*,0),
        "LINK_TO" VARCHAR2(20),
        "LINK_TO_TYPE" CHAR(3),
        "STATUS" CHAR(6),
        "CUST_ACTIVATION_DT" DATE,
        "LINK_CMD" CHAR(3)
   );



CREATE TABLE "SIM_ACTIVATION_LINK_EXPIRED"
   (    "ID" NUMBER NOT NULL ENABLE,
        "CUSTOMER_TYPE" VARCHAR2(16) NOT NULL ENABLE,
        "MSISDN" NUMBER NOT NULL ENABLE,
        "LINK_TO" VARCHAR2(12) NOT NULL ENABLE,
        "LINK_TO_TYPE" VARCHAR2(12) NOT NULL ENABLE,
        "STATUS" VARCHAR2(12) NOT NULL ENABLE,
        "CUST_ACTIVATION_DT" DATE,
        "CUST_DEACTIVATION_DT" DATE,
        "DT_CREATED" DATE,
        "DT_MODIFIED" DATE,
        "LINK_CMD" VARCHAR2(12) NOT NULL ENABLE,
        "ODS_LAST_CHK_DT" DATE,
        "EXPIRY_DATE" DATE
   );



CREATE TABLE "SIM_DEACT_LINKS_ERR_BULK"
   (    "DT_CREATED" DATE,
        "BULK_GRP_ID" VARCHAR2(30),
        "REASON" VARCHAR2(512),
        "TRAN_DT" DATE,
        "CREATED_BY" VARCHAR2(30),
        "REMARKS" VARCHAR2(512),
        "LOCAL_SIM" NUMBER,
        "OFW_SIM" NUMBER
   );



CREATE TABLE "SIM_SERVICES"
   (    "ID" NUMBER NOT NULL ENABLE,
        "MSISDN" NUMBER NOT NULL ENABLE,
        "SERVICE_CODE" VARCHAR2(30) NOT NULL ENABLE,
        "ACTIVATION_DT" DATE,
        "DEACTIVATION_DT" DATE,
        "STATUS" VARCHAR2(12) NOT NULL ENABLE,
         CONSTRAINT "SIM_SERVICES_PK" PRIMARY KEY ("ID"),
         CONSTRAINT "SIM_SERVICES_UK" UNIQUE ("MSISDN")
   );



CREATE TABLE "SSET_MAPPING"
   (    "ID" NUMBER NOT NULL ENABLE,
        "MSISDN_FR" NUMBER NOT NULL ENABLE,
        "MSISDN_TO" NUMBER NOT NULL ENABLE,
        "SSET_ID" NUMBER,
        "IRSSET" NUMBER NOT NULL ENABLE,
        "NORMALSSET" NUMBER NOT NULL ENABLE,
        "STATUS" VARCHAR2(12) NOT NULL ENABLE,
        "CREATED_BY" VARCHAR2(30),
        "DT_CREATED" DATE,
        "UPDATED_BY" VARCHAR2(30),
        "DT_UPDATED" DATE,
         CONSTRAINT "SSET_MAPPING_PK" PRIMARY KEY ("ID"),
         CONSTRAINT "SSET_MAPPING_UK" UNIQUE ("MSISDN_FR")
   );



CREATE TABLE "SWEDEN_NSN_MAPPING"
   (    "ID" NUMBER NOT NULL ENABLE,
        "MSISDN_FR" NUMBER NOT NULL ENABLE,
        "MSISDN_TO" NUMBER NOT NULL ENABLE,
        "STATUS" VARCHAR2(12) NOT NULL ENABLE,
        "CREATED_BY" VARCHAR2(30),
        "DT_CREATED" DATE,
        "UPDATED_BY" VARCHAR2(30),
        "DT_UPDATED" DATE,
         CONSTRAINT "SNSN_MAPPING_PK" PRIMARY KEY ("ID"),
         CONSTRAINT "SNSN_MAPPING_UK" UNIQUE ("MSISDN_FR")
   );



CREATE TABLE "SWITCH"
   (    "ID" NUMBER NOT NULL ENABLE,
        "CUSTOMER_TYPE" VARCHAR2(16) NOT NULL ENABLE,
        "MSISDN" NUMBER NOT NULL ENABLE,
        "LINK_TO" VARCHAR2(12) NOT NULL ENABLE,
        "LINK_TO_TYPE" VARCHAR2(12) NOT NULL ENABLE,
        "STATUS" VARCHAR2(12) NOT NULL ENABLE,
        "CUST_ACTIVATION_DT" DATE,
        "CUST_DEACTIVATION_DT" DATE,
        "DT_CREATED" DATE,
        "DT_MODIFIED" DATE,
        "LINK_CMD" VARCHAR2(12) NOT NULL ENABLE,
        "ODS_LAST_CHK_DT" DATE,
        "EXPIRY_DATE" DATE,
        "CUST_ACTIVATION_TM" DATE,
        "CUST_DEACTIVATION_TM" DATE,
        "NOTIFY_DATE" DATE,
        "CS_USERNAME" VARCHAR2(30),
        "BULK_GRP_ID" VARCHAR2(30),
         CONSTRAINT "SWITCH_PK" PRIMARY KEY ("MSISDN", "LINK_TO")
   );



CREATE TABLE "SWITCHED"
   (    "ID" NUMBER NOT NULL ENABLE,
        "CUSTOMER_TYPE" VARCHAR2(16) NOT NULL ENABLE,
        "LINK_TO" VARCHAR2(12) NOT NULL ENABLE,
        "MSISDN" NUMBER NOT NULL ENABLE,
        "LINK_TO_TYPE" VARCHAR2(12) NOT NULL ENABLE,
        "STATUS" VARCHAR2(12) NOT NULL ENABLE,
        "CUST_ACTIVATION_DT" DATE,
        "CUST_DEACTIVATION_DT" DATE,
        "DT_CREATED" DATE,
        "DT_MODIFIED" DATE,
        "LINK_CMD" VARCHAR2(12) NOT NULL ENABLE,
        "ODS_LAST_CHK_DT" DATE,
        "EXPIRY_DATE" DATE,
        "CUST_ACTIVATION_TM" DATE,
        "CUST_DEACTIVATION_TM" DATE,
        "NOTIFY_DATE" DATE,
        "CS_USERNAME" VARCHAR2(30),
        "BULK_GRP_ID" VARCHAR2(30)
   );



CREATE TABLE "SYSTEM_LOG"
   (    "SOURCE" VARCHAR2(60),
        "INFO" VARCHAR2(1024),
        "DT_CREATED" DATE,
        "ID" NUMBER
   );



CREATE TABLE "SYSTEM_MSG"
   (    "MESSAGE_ID" VARCHAR2(64) NOT NULL ENABLE,
         CONSTRAINT "SYSTEM_MSG_PK" PRIMARY KEY ("MESSAGE_ID")
   );



CREATE TABLE "TAGGING"
   (    "NEXTVAL" NUMBER,
        "MSISDN" NUMBER NOT NULL ENABLE,
        "COUNTRY" VARCHAR2(30),
        "SUBSCRIBER_NAME" VARCHAR2(60),
        "NAME_OF_REQ_PARTY" VARCHAR2(60),
        "ACTIVATION_DT" DATE,
        "REACTIVATION_DT" DATE,
        "STATUS" VARCHAR2(12),
        "DEACTIVATION_DT" DATE,
        "DEACTIVATION_REASON" VARCHAR2(128),
        "CS_USERNAME" VARCHAR2(30),
        "CREATED_BY" VARCHAR2(30),
        "DT_CREATED" DATE,
        "UPDATED_BY" VARCHAR2(30),
        "DT_UPDATED" DATE,
        "REQUEST_ORIGIN" VARCHAR2(8) NOT NULL ENABLE,
        "REMARKS" VARCHAR2(255),
        "DAILY_BAL" NUMBER(8,2),
        "MIN_BAL" NUMBER(8,2),
        "DURATION" NUMBER(3,0),
        "EXTENDED" NUMBER(1,0),
        "BREATHING_PERIOD" NUMBER(4,0),
        "LAST_DAILY_BAL_CHK" DATE,
        "LAST_COUNTRY_CHK" DATE,
        "HOT_COUNTRY_CNT" NUMBER,
        "IMSI" VARCHAR2(30),
        "LAST_DAILY_BAL" NUMBER,
        "LAST_DAILY_BAL_CTR" NUMBER(2,0) NOT NULL ENABLE,
        "CUSTOMER_TYPE" VARCHAR2(16) NOT NULL ENABLE,
        "COUNTRY_NAME" VARCHAR2(60),
        "BREATHING_PERIOD_DT" DATE,
        "HOT_COUNTRY_DT" DATE,
        "HOT_COUNTRY_DURATION" NUMBER,
        "DEACT_BASIS_DT" DATE,
        "HOT_COUNTRY_MAX_DURATION" NUMBER(6,0),
        "ACTIVATION_TM" DATE,
        "DEACTIVATION_TM" DATE,
        "NOTIFY_DATE" DATE,
        "DT_MIGRATED" DATE
   );



CREATE TABLE "TAG_PAIR"
   (    "MSISDN" NUMBER NOT NULL ENABLE,
        "LINK_TO" VARCHAR2(12) NOT NULL ENABLE
   );



CREATE TABLE "TMP"
   (    "ID" NUMBER NOT NULL ENABLE,
        "MSISDN" NUMBER NOT NULL ENABLE,
        "COUNTRY" VARCHAR2(30),
        "SUBSCRIBER_NAME" VARCHAR2(60),
        "NAME_OF_REQ_PARTY" VARCHAR2(60),
        "ACTIVATION_DT" DATE,
        "REACTIVATION_DT" DATE,
        "STATUS" VARCHAR2(12),
        "DEACTIVATION_DT" DATE,
        "DEACTIVATION_REASON" VARCHAR2(128),
        "CS_USERNAME" VARCHAR2(30),
        "CREATED_BY" VARCHAR2(30),
        "DT_CREATED" DATE,
        "UPDATED_BY" VARCHAR2(30),
        "DT_UPDATED" DATE,
        "REQUEST_ORIGIN" VARCHAR2(8) NOT NULL ENABLE,
        "REMARKS" VARCHAR2(255),
        "DAILY_BAL" NUMBER(8,2),
        "MIN_BAL" NUMBER(8,2),
        "DURATION" NUMBER(3,0),
        "EXTENDED" NUMBER(1,0),
        "BREATHING_PERIOD" NUMBER(4,0),
        "LAST_DAILY_BAL_CHK" DATE,
        "LAST_COUNTRY_CHK" DATE,
        "HOT_COUNTRY_CNT" NUMBER,
        "IMSI" VARCHAR2(30),
        "LAST_DAILY_BAL" NUMBER,
        "LAST_DAILY_BAL_CTR" NUMBER(2,0) NOT NULL ENABLE,
        "CUSTOMER_TYPE" VARCHAR2(16) NOT NULL ENABLE,
        "COUNTRY_NAME" VARCHAR2(60),
        "BREATHING_PERIOD_DT" DATE,
        "HOT_COUNTRY_DT" DATE,
        "HOT_COUNTRY_DURATION" NUMBER,
        "DEACT_BASIS_DT" DATE,
        "HOT_COUNTRY_MAX_DURATION" NUMBER(6,0),
        "ACTIVATION_TM" DATE,
        "DEACTIVATION_TM" DATE,
        "NOTIFY_DATE" DATE,
        "DT_MIGRATED" DATE
   );



CREATE TABLE "TMP2"
   (    "A_NO" VARCHAR2(20) NOT NULL ENABLE
   );



CREATE TABLE "TMP_ACT"
   (    "MSISDN" NUMBER NOT NULL ENABLE,
        "CUST_ACTIVATION_DT" DATE,
        "CUSTOMER_TYPE" CHAR(3),
        "STATUS" CHAR(6)
   );



CREATE TABLE "TMP_MCC_MESSAGES"
   (    "ID" NUMBER NOT NULL ENABLE,
        "MCC" VARCHAR2(60) NOT NULL ENABLE,
        "MESSAGE_TYPE" VARCHAR2(30) NOT NULL ENABLE,
        "MSG" VARCHAR2(2000) NOT NULL ENABLE,
        "DT_CREATED" DATE NOT NULL ENABLE
   );



CREATE TABLE "TRANSACTION_LOG"
   (    "ID" NUMBER NOT NULL ENABLE,
        "REF_ID" NUMBER NOT NULL ENABLE,
        "GSMNUM" VARCHAR2(12) NOT NULL ENABLE,
        "STEP_NO" NUMBER(4,0) DEFAULT 0 NOT NULL ENABLE,
        "STATUS" NUMBER(4,0) DEFAULT 0 NOT NULL ENABLE,
        "TX_START" DATE NOT NULL ENABLE,
        "TX_END" DATE,
        "TRAN_DT" DATE,
         CONSTRAINT "TX_LOG_PK" PRIMARY KEY ("ID")
   );



CREATE TABLE "TRG"
   (    "MSISDN" NUMBER NOT NULL ENABLE
   );



CREATE TABLE "UPLOAD"
   (    "MSISDN" NUMBER NOT NULL ENABLE
   );



CREATE TABLE "USER_LOG"
   (    "ID" NUMBER(11,0) NOT NULL ENABLE,
        "USER_CODE" VARCHAR2(30),
        "ROLE_CODE" VARCHAR2(100),
        "MOD_NAME" VARCHAR2(255),
        "IP_ADDR" VARCHAR2(22),
        "URL" VARCHAR2(512),
        "LOGS" VARCHAR2(2048),
        "CREATED_BY" VARCHAR2(32) NOT NULL ENABLE,
        "DT_CREATED" DATE NOT NULL ENABLE,
        "UPDATED_BY" VARCHAR2(32),
        "DT_UPDATED" DATE,
        "MSISDN" VARCHAR2(14),
         CONSTRAINT "USLO_PK" PRIMARY KEY ("ID")
   );



CREATE TABLE "USER_MASTER"
   (    "USER_ID" NUMBER(11,0) NOT NULL ENABLE,
        "USER_CODE" VARCHAR2(20) NOT NULL ENABLE,
        "PASSWORD" VARCHAR2(64) NOT NULL ENABLE,
        "LAST_NAME" VARCHAR2(255),
        "FIRST_NAME" VARCHAR2(255),
        "ADDRESS" VARCHAR2(255),
        "EMAIL" VARCHAR2(255),
        "POSITION" VARCHAR2(255),
        "DEPARTMENT" VARCHAR2(255),
        "TELNO" VARCHAR2(13),
        "GSMNUM" VARCHAR2(13),
        "ROLE_CODE" VARCHAR2(30) NOT NULL ENABLE,
        "PASS_EXP_N_DAYS" NUMBER(11,0) NOT NULL ENABLE,
        "PASS_EXP_DT" DATE,
        "LOGIN" DATE,
        "LOGOUT" DATE,
        "LOCKOUT" NUMBER,
        "LOCKOUT_CTR" NUMBER DEFAULT 0,
        "IS_LOGIN" NUMBER DEFAULT 0,
        "ON_FIRST_LOGIN" NUMBER DEFAULT 0,
        "CREATED_BY" VARCHAR2(32) NOT NULL ENABLE,
        "DT_CREATED" DATE NOT NULL ENABLE,
        "UPDATED_BY" VARCHAR2(32),
        "DT_UPDATED" DATE,
         CONSTRAINT "USMA_PK" PRIMARY KEY ("USER_ID"),
         CONSTRAINT "USMA_UK" UNIQUE ("USER_CODE")
   );



CREATE TABLE "USER_ROLES"
   (    "ID" NUMBER(11,0) NOT NULL ENABLE,
        "ROLE_CODE" VARCHAR2(30),
        "ROLE_DESC" VARCHAR2(255),
        "CREATED_BY" VARCHAR2(32) NOT NULL ENABLE,
        "DT_CREATED" DATE NOT NULL ENABLE,
        "UPDATED_BY" VARCHAR2(32),
        "DT_UPDATED" DATE,
         CONSTRAINT "USRO_PK" PRIMARY KEY ("ID"),
         CONSTRAINT "ROLE_UK" UNIQUE ("ROLE_CODE")
   );



CREATE TABLE "USURF_COUNTRIES"
   (    "ID" NUMBER NOT NULL ENABLE,
        "COUNTRY" VARCHAR2(10) NOT NULL ENABLE,
        "SERVICE_ID" VARCHAR2(30) NOT NULL ENABLE,
        "STATUS" VARCHAR2(12) NOT NULL ENABLE,
        "ROAMING_PARTNER" VARCHAR2(30) NOT NULL ENABLE,
        "TZ" VARCHAR2(10) NOT NULL ENABLE,
        "CREATED_BY" VARCHAR2(30),
        "DT_CREATED" DATE,
        "UPDATED_BY" VARCHAR2(30),
        "DT_UPDATED" DATE,
         CONSTRAINT "USURF_COUNTRIES_PK" PRIMARY KEY ("ID"),
         CONSTRAINT "USURF_COUNTRIES_UK" UNIQUE ("COUNTRY"),
         CONSTRAINT "USURF_COUNTRIES_SVC_UK" UNIQUE ("SERVICE_ID")
   );



CREATE TABLE "USURF_ACTIVATION"
   (    "ID" NUMBER NOT NULL ENABLE,
        "MSISDN" NUMBER NOT NULL ENABLE,
        "COUNTRY" VARCHAR2(30),
        "DENOM" NUMBER(3,0),
        "ACTIVATION_DT" DATE,
        "STATUS" VARCHAR2(12),
        "DEACTIVATION_DT" DATE,
        "DEACTIVATION_REASON" VARCHAR2(128),
        "CREATED_BY" VARCHAR2(30),
        "DT_CREATED" DATE,
        "UPDATED_BY" VARCHAR2(30),
        "DT_UPDATED" DATE,
        "REMARKS" VARCHAR2(255),
         CONSTRAINT "USURF_ACT_PK" PRIMARY KEY ("ID"),
         CONSTRAINT "USURF_ACT_UK" UNIQUE ("MSISDN","COUNTRY"),
         CONSTRAINT "USURF_COUNTRY_FK" FOREIGN KEY ("COUNTRY")
          REFERENCES "USURF_COUNTRIES" ("COUNTRY") ENABLE
   );



CREATE TABLE "WHITELISTED_ERR_LOG"
   (    "MSISDN" VARCHAR2(30),
        "DT_CREATED" DATE,
        "REMARKS" VARCHAR2(255),
        "TRAN_DT" DATE,
        "CREATED_BY" VARCHAR2(30),
        "BULK_GRP_ID" VARCHAR2(30),
        "REASON" VARCHAR2(128)
   );



CREATE TABLE "WHITELISTED_LOG"
   (    "MSISDN" NUMBER NOT NULL ENABLE,
        "DT_CREATED" DATE NOT NULL ENABLE,
        "REMARKS" VARCHAR2(255),
        "TRAN_DT" DATE,
        "CREATED_BY" VARCHAR2(30),
        "BULK_GRP_ID" VARCHAR2(30),
         CONSTRAINT "WLISTED_LOG_PK" PRIMARY KEY ("MSISDN")
   );



CREATE TABLE "ZONES"
   (    "ID" NUMBER NOT NULL ENABLE,
        "ZONE_ID" NUMBER NOT NULL ENABLE,
        "BREATHING_PERIOD" NUMBER DEFAULT 0 NOT NULL ENABLE,
        "STATUS" VARCHAR2(12) NOT NULL ENABLE,
        "CREATED_BY" VARCHAR2(30),
        "DT_CREATED" DATE,
        "UPDATED_BY" VARCHAR2(30),
        "DT_UPDATED" DATE,
        "MAX_DURATION" NUMBER,
         CONSTRAINT "ZONES_PK" PRIMARY KEY ("ID"),
         CONSTRAINT "ZONES_UK" UNIQUE ("ZONE_ID")
   );



PROMPT Create oracle sequence...
CREATE SEQUENCE  "ACL_SEQ"  MINVALUE 1 MAXVALUE 1000000000000000000000000000 INCREMENT BY 1 START WITH 118 NOCACHE  ORDER  NOCYCLE;
CREATE SEQUENCE  "ARDSREQUEST_ID_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  ORDER  NOCYCLE;
CREATE SEQUENCE  "ARDSRESPONSE_ID_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 496495 NOCACHE  ORDER  NOCYCLE;
CREATE SEQUENCE  "BROADCAST_LOG_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 254478 NOCACHE  ORDER  NOCYCLE;
CREATE SEQUENCE  "CCB_LOG_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1293007 NOCACHE  ORDER  NOCYCLE;
CREATE SEQUENCE  "COUNTRIES_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 293 NOCACHE  ORDER  NOCYCLE;
CREATE SEQUENCE  "CUSTOMER_TYPES_MAPPING_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 159585 NOCACHE  ORDER  NOCYCLE;
CREATE SEQUENCE  "CUSTOMER_TYPES_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 24 NOCACHE  ORDER  NOCYCLE;
CREATE SEQUENCE  "DAILYBAL_LOG_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 164 NOCACHE  ORDER  NOCYCLE;
CREATE SEQUENCE  "DEFAULT_UNLI_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 164 NOCACHE  ORDER  NOCYCLE;
CREATE SEQUENCE  "FUN_CUSTOMER_TYPES_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 4 NOCACHE  ORDER  NOCYCLE;
CREATE SEQUENCE  "FUN_SIM_ACTIVATION_LINKS_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  ORDER  NOCYCLE;
CREATE SEQUENCE  "GEO_PROBE_LOG_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1203 NOCACHE  ORDER  NOCYCLE;
CREATE SEQUENCE  "HLR_IMSI_MAPPING_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 47 NOCACHE  ORDER  NOCYCLE;
CREATE SEQUENCE  "HLR_SERVERS_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 37 NOCACHE  ORDER  NOCYCLE;
CREATE SEQUENCE  "HLR_SERVER_MAPPING_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1874 NOCACHE  ORDER  NOCYCLE;
CREATE SEQUENCE  "IN_SERVERS_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 9 NOCACHE  ORDER  NOCYCLE;
CREATE SEQUENCE  "IN_SERVER_MAPPING_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 380 NOCACHE  ORDER  NOCYCLE;
CREATE SEQUENCE  "KEYWORDREQUEST_ID_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 169242 NOCACHE  ORDER  NOCYCLE;
CREATE SEQUENCE  "KEYWORDS_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 17 NOCACHE  ORDER  NOCYCLE;
CREATE SEQUENCE  "KEYWORD_MSG_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 251 NOCACHE  ORDER  NOCYCLE;
CREATE SEQUENCE  "MANUAL_ENROLLMENT_LOG_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1475070 NOCACHE  ORDER  NOCYCLE;
CREATE SEQUENCE  "MODULES_SEQ"  MINVALUE 1 MAXVALUE 1000000000000000000000000000 INCREMENT BY 1 START WITH 64 NOCACHE  ORDER  NOCYCLE;
CREATE SEQUENCE  "ODS_LOG_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 5 NOCACHE  ORDER  NOCYCLE;
CREATE SEQUENCE  "PASS_LOG_SEQ"  MINVALUE 1 MAXVALUE 1000000000000000000000000000 INCREMENT BY 1 START WITH 30243 NOCACHE  ORDER  NOCYCLE;
CREATE SEQUENCE  "PLMN_MAPPING_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1374 NOCACHE  ORDER  NOCYCLE;
CREATE SEQUENCE  "RADCOM_DOWNLOADED_FILES_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 3905469 NOCACHE  ORDER  NOCYCLE;
CREATE SEQUENCE  "REQUEST_LOG_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 3905469 NOCACHE  ORDER  NOCYCLE;
CREATE SEQUENCE  "RESPONSE_LOG_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 4618657 NOCACHE  ORDER  NOCYCLE;
CREATE SEQUENCE  "SERVICES_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 8 NOCACHE  ORDER  NOCYCLE;
CREATE SEQUENCE  "SIM_ACTIVATION_HISTORY_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 508654 NOCACHE  ORDER  NOCYCLE;
CREATE SEQUENCE  "SIM_ACTIVATION_LINKS_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 635907 NOCACHE  ORDER  NOCYCLE;
CREATE SEQUENCE  "SIM_ACTIVATION_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 2676711 NOCACHE  ORDER  NOCYCLE;
CREATE SEQUENCE  "SIM_SERVICES_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  ORDER  NOCYCLE;
CREATE SEQUENCE  "SSET_MAPPING_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 2453 NOCACHE  ORDER  NOCYCLE;
CREATE SEQUENCE  "SSET_MAPPING_SSET_ID_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 3389 NOCACHE  ORDER  NOCYCLE;
CREATE SEQUENCE  "SYSTEM_LOG_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 135437339 NOCACHE  ORDER  NOCYCLE;
CREATE SEQUENCE  "TRANSACTION_LOG_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  ORDER  NOCYCLE;
CREATE SEQUENCE  "USER_LOG_SEQ"  MINVALUE 1 MAXVALUE 1000000000000000000000000000 INCREMENT BY 1 START WITH 3788029 NOCACHE  ORDER  NOCYCLE;
CREATE SEQUENCE  "USER_MASTER_SEQ"  MINVALUE 1 MAXVALUE 1000000000000000000000000000 INCREMENT BY 1 START WITH 10458 NOCACHE  ORDER  NOCYCLE;
CREATE SEQUENCE  "USER_ROLES_SEQ"  MINVALUE 1 MAXVALUE 1000000000000000000000000000 INCREMENT BY 1 START WITH 27 NOCACHE  ORDER  NOCYCLE;
CREATE SEQUENCE  "USURF_COUNTRIES_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 47 NOCACHE  ORDER  NOCYCLE;
CREATE SEQUENCE  "USURF_ACTIVATION_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 47 NOCACHE  ORDER  NOCYCLE;
CREATE SEQUENCE  "ZONES_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 6 NOCACHE  ORDER  NOCYCLE;
