select s.SERVER_IP, s.SERVER_PORT, s.SERVER_NAME, s.USERNAME, s.PASSWORD, s.TIMEOUT, s.RETRY_CNT, m.IMSI
from   HLR_SERVERS s, HLR_IMSI_MAPPING m
where  s.SERVER_IP = m.SERVER_IP 
and    (m.IMSI = substr('515021808853427', 1, 7));
